src/Application/Contracts/ISessionService.cs, src/Application/Models/Participants/ParticipantDetailsModel.cs, src/Domain/Entities/Participants/ParticipantDetails.cs, src/Infrastructure/Services/SessionService.cs, src/StudyApi/Common/SessionExpiryMiddleware.cs, src/StudyApi/Controllers/V1/Users/UsersController.cs, src/StudyApi/DependencyRegistrations/InfrastructureRegistration.cs, src/StudyApi/Startup.cs
Session ID is added to the user in the DB when loggining in, it is then checked on each request via middleware.  If this sessionID does not match then their session is invalidated and they are logged out
=> Stop concurrent logins

src/Application/Contracts/IUserService.cs, src/Application/Users/V1/Commands/ChangePasswordCommand.cs, src/Infrastructure/Services/UserService.cs
Initiate auth challenge was causing a MFA challenge instead of auth response so I am using AdminSetUserPasswordAsync instead
=> Fixed password update

src/Application/Responses/V1/Users/SignUpResponse.cs, src/Infrastructure/Services/UserService.cs, src/StudyApi/Controllers/V1/Users/UsersController.cs
Pass back generic messages regardless wether its a success or failure
=> user enumeration fix

.github/workflows/bpor_rms_build.yml, .github/workflows/bpor_rms_manual_deploy.yml, .github/workflows/ci.yml, .github/workflows/oat_manual.yml, .github/workflows/pr.yml, .github/workflows/prod_manual.yml, .github/workflows/qa_manual.yml, .github/workflows/sq.yml, .github/workflows/staged_deployment.yml, .github/workflows/stream_handler_staged_deploy.yml, .github/workflows/uat_manual.yml
replacing NUGET_PACKAGE_TOKEN secret with GITHUB_TOKEN to use Github App authentication to retrieve packages in all workflows
=> add GITHUB_TOKEN and update job version

BPOR/BPOR.Rms/Controllers/AccountController.cs, BPOR/BPOR.Rms/Controllers/EmailController.cs, BPOR/BPOR.Rms/IdgAuthenticationMiddleware.cs, BPOR/BPOR.Rms/Program.cs, BPOR/BPOR.Rms/RmsSettings.cs, BPOR/BPOR.Rms/Services/ITransactionalEmailService.cs, BPOR/BPOR.Rms/Services/TransactionalEmailService.cs, BPOR/BPOR.Rms/Startup/DependencyInjection.cs, BPOR/BPOR.Rms/Views/Account/SignedOut.cshtml, BPOR/BPOR.Rms/Views/Email/Partials/_Footer.cshtml
[No notification emails received when emails sent](https://nihr.atlassian.net/browse/CRNCC-2271)
- Added transactional email service to handle non-campaign emails.
- Send notification emails when campaign is sent.
- Minor tidy up in AccountController.
- DI tidy up.
- IDG bypass fix.
=> CRNCC-2271 - Send campaign notification email

BPOR/BPOR.Rms/Views/Filter/Partials/_VolunteerInclusionExclusionCriteria.cshtml, BPOR/BPOR.Rms/Views/Study/Partials/Index/_StudyListHeader.cshtml
https://nihr.atlassian.net/browse/CRNCC-2211
- Updated casing to sentence casing in headers
=> CRNCC-2211 - Correct page casing

BPOR/BPOR.Rms/Views/Study/Partials/Index/_StudyListHeader.cshtml
changed apply to add a study to primary button class
=>  CRNCC-2284  Incorrect button used on "My studies" page (researcher view)

BPOR/BPOR.Rms/Views/Shared/_Header.cshtml, BPOR/BPOR.Rms/wwwroot/css/bpor.css
added class new class headerImage to header logos, class changes focus and hover to match VS and BPoR and also footer regional logos.
=> added headerImage class for correct focus/hover style.

BPOR/BPOR.Rms/Models/Researcher/ResearcherStudyFormViewModel.cs, BPOR/BPOR.Rms/Views/Researcher/Partials/_Step8FormFields.cshtml
added method to return a string in the common uk format for display.
=> CRNCC-2275

BPOR/BPOR.Rms/Views/Shared/_Header.cshtml, BPOR/BPOR.Rms/wwwroot/css/bpor.css
style change to the header to show yellow outline on focus.
html width attribute and css change to bpor logo for browser compatibility.
=> CRNCC 2266

BPOR/BPOR.Rms/wwwroot/css/bpor.css
fixed capitalisation in css id selector.
=> fixing css spelling mistak.

BPOR/BPOR.Rms/Views/Home/Index.cshtml
[changed style for inset text landing page, ](https://nihr.atlassian.net/browse/CRNCC-2249)
changed style for text in inset block so all text style matches.
changed wording to include NIHR.
=> Rms fix/crncc 2249

BPOR/BPOR.Rms/Views/Email/Partials/_TemplateSelect.cshtml, BPOR/BPOR.Rms/wwwroot/css/nihr-component-ui.css
Override styles to use grey borders in line with volunteer site
=> Crncc 2210 radio checkbox style update

BPOR/BPOR.Rms/Controllers/ResearcherController.cs, BPOR/BPOR.Rms/Models/Researcher/ResearcherStudyFormViewModel.cs, BPOR/BPOR.Rms/Models/Study/StudyFormEditModel.cs, BPOR/BPOR.Rms/Views/Email/EmailSuccess.cshtml, BPOR/BPOR.Rms/Views/Researcher/AddStudySuccess.cshtml, BPOR/BPOR.Rms/Views/Researcher/Edit.cshtml, BPOR/BPOR.Rms/Views/Researcher/SubmitStudy.cshtml, BPOR/BPOR.Rms/Views/Shared/_Layout.cshtml, BPOR/BPOR.Rms/Views/Study/Create.cshtml, BPOR/BPOR.Rms/Views/Study/Details.cshtml, BPOR/BPOR.Rms/Views/Study/Edit.cshtml, BPOR/NIHR.GovUk.AspNetCore.Mvc/FormWithSteps.cs
https://nihr.atlassian.net/browse/CRNCC-2293
updated page titles,
created method in researcher controller for page titles in the apply to add study route.
=> Rms fix/crncc 2293-page-titles

BPOR/BPOR.Rms/Controllers/ResearcherController.cs, BPOR/BPOR.Rms/Controllers/StudyController.cs
model Id was not passed in method so the dependant question did not have it to link back to in both the cancel button as well as the breadcrumbs.
https://nihr.atlassian.net/browse/CRNCC-2286
=> CRNCC-2286 cancel away from editing dependent

src/Infrastructure/Services/AuthenticationService.cs
updated response on userNameExists exception to a generic success response.
=> CRNCC-2111 PRB0040351: Wrong page displayed when trying to re-register account

BPOR/BPOR.Rms/TagHelpers/AreasOfResearchSelectListTagHelper.cs, BPOR/BPOR.Rms/Views/Shared/Partials/_AreasOfResearch.cshtml, BPOR/BPOR.Rms/Views/Volunteer/Create.cshtml
previously removed labels in legends causing some css to be lost
=> feat: resolve heading levels

BPOR/BPOR.Content/Views/Home/Index.cshtml, BPOR/BPOR.Content/Views/Shared/_Layout.cshtml, BPOR/BPOR.Content/wwwroot/resources/css/join.css
Updated styling of Carousel, removing pager pips and forcing live updates to read changes
Tested with nvda to ensure that carousel content is read out when the buttons are used
=> CRNCC-2517 - Removal of dot toggles and repositioning of the arrow toggles on the Campaign page

BPOR/BPOR.Content/Views/Home/Index.cshtml
added a temporary passthrough of URL query string to the VS link so campaigns can be tracked through the campaign page to VS
=> added queryString to VS link on campaign page.

BPOR/BPOR.Domain/Entities/DynamoParticipantAddress.cs, BPOR/BPOR.Domain/Entities/ParticipantAddress.cs, BPOR/BPOR.Domain/Migrations/20250516091710_CRNCC-2479-Canonical-Town-data.Designer.cs, BPOR/BPOR.Domain/Migrations/20250516091710_CRNCC-2479-Canonical-Town-data.cs, BPOR/BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/Handlers/StreamHandler.cs, BPOR/BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/Mappers/ParticipantMapper.cs
Added a new field to the participant address table, 'CanonicalTown'
Update the view to use the new canonical town field 
Update the stream handler to populate the CanonicalTown field is possible on insert/modify
=> Add Canonical Town To Reporting In Place Of Town

BPOR/BPOR.Rms/Models/Filter/PostcodeSearchModel.cs
[CRNCC-2131](https://nihr.atlassian.net/browse/CRNCC-2131)
Add appropriate validation error when the location of a postcode cannot be found when filtering.
=> CRNCC-2131 - Add appropriate validation error when the location of a postcode cannot be found.

BPOR/NIHR.Infrastructure.EntityFrameworkCore.MySql/DBSettingsExtensions.cs, BPOR/NIHR.Infrastructure.EntityFrameworkCore/Settings/DbSettings.cs
https://nihr.atlassian.net/browse/CRNCC-2653
=> Merge CRNCC-2653 into rc/rms/v1.3.2

BPOR/BPOR.Rms/Controllers/FilterController.cs, BPOR/BPOR.Rms/Views/Filter/Partials/_FilterButtonsAndCount.cshtml
https://nihr.atlassian.net/browse/CRNCC-2645
=> Merge CRNCC-2645 into Rework-Added-RMS

BPOR/BPOR.Rms/Controllers/FilterController.cs, BPOR/BPOR.Rms/Views/Filter/Partials/_FilterButtonsAndCount.cshtml
Reverts PA-NIHR-CRN/dte-study-api#263
=> Revert "Merge CRNCC-2645 into Rework-Added-RMS"

BPOR/BPOR.Rms/Controllers/FilterController.cs, BPOR/BPOR.Rms/Views/Filter/Partials/_FilterButtonsAndCount.cshtml
I thought I'd made a mistake when merging the original branch and reverted it to avoid causing further issues. After discussing the issue it transpired that I didn't make a mistake, so reverting the revert!
Reverts PA-NIHR-CRN/dte-study-api#266
=> Revert "Revert "Merge CRNCC-2645 into Rework-Added-RMS""

BPOR/BPOR.Domain/Entities/FilterCriteria.cs, BPOR/BPOR.Domain/Entities/FilterHasLongTermCondition.cs, BPOR/BPOR.Domain/Entities/ParticipantDbContext.cs, BPOR/BPOR.Domain/Migrations/20250627083237_AddHasLongTermConditionToFilter.Designer.cs, BPOR/BPOR.Domain/Migrations/20250627083237_AddHasLongTermConditionToFilter.cs, BPOR/BPOR.Rms/Controllers/FilterController.cs, BPOR/BPOR.Rms/Mappers/FilterMapper.cs, BPOR/BPOR.Rms/Models/Filter/VolunteerFilterViewModel.cs, BPOR/BPOR.Rms/ParticipantQueryExtensions.cs, BPOR/BPOR.Rms/Services/CampaignService.cs, BPOR/BPOR.Rms/Views/Filter/Partials/_Demographics.cshtml, BPOR/BPOR.Rms/VolunteerFilterExtensions.cs
https://nihr.atlassian.net/browse/CRNCC-2655
=> Merge Rms/crncc 2655 filter long term conditions into rework-added-RMS
